"""
Django settings for bookmarks project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t$4c*x$0qc+61+n6$wl(e%h$--2$^!s1ocr^_u&@mrq2cw-q5#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['mysite.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    # django.contrib.admin 앱에는 account 애플리케이션에서 재정의할 표준 인증 템플릿이 포함되어 있다.
    # account.apps.AccountConfig을 먼저 배치하면 django.contrib.admin에 포함된 인증 템플릿 대신 커스텀 인증 템플릿이 기본적으로 사용된다.
    'account.apps.AccountConfig',
    'django.contrib.admin',
    # 인증 프레임워크는 django.contrib.auth 에 있으며 다른 장고 contrib 패키지들에서 사용된다.
    # startproject 명령을 사용해서 새로운 프로젝트를 생성하면 프로젝트의 기본 설정에 인증 프레임워크가 포함된다.
    # 이것은 django.contrib.auth 애플리케이션과 프로젝트의 MIDDLEWARE설정에 있는 다음 두 미들웨어 클래스로 구성된다.
    # AuthenticationMiddleware : 세션을 사용해서 사용자와 요청을 연결한다.
    # SessionMiddleware : 요청 간에 현재 세션을 처리한다
    # 인증 프레임워크에는 django.contrib.auth.models 정의된 다음의 모델도 포함된다.
    # User : 기본 필드들을 가진 사용자 모델이다.
    # Group : 사용자를 분류하기 위한 그룹 모델이다.
    # Permission: 사용자 또는 그룹이 특정 작업을 수행하기 위한 플래그
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'django_extensions',
    'images.apps.ImagesConfig',
    'easy_thumbnails',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookmarks.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmarks.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 요청에 next 매개 변수가 없는 경우 성공적인 로그인 후 사용자를 리디렉션할 URL을 장고에게 알려준다.
LOGIN_REDIRECT_URL = 'dashboard'
# 로그인하도록 사용자를 리디렉션하는 URL이다.
LOGIN_URL = 'login'
# 사용자가 로그아웃하도록 리디렉션 하는 URL이다.
LOGOUT_URL = 'logout'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 프로젝트에서 사용가능한 인증 백엔드 목록이 포함된다.
# ModelBackend는 django.contrib.auth의 User 모델을 사용해서 데이터베이스에 사용자를 인증한다.
# 커스텀 백엔드를 만들어 LDAP 디렉터리 또는 기타 시스템과 같은 다른 소스에도 사용자를 인증할 수 있다.
# AUTHENTICATION : request 객체 및 사용자 자격 증명을 매개 변수로 사용한다. 자격증명이 유효하면 해당 자격 증명과 일치하는 user객체를 반환하고 그렇지 않으면 None을 반환해야 한다.
#                  request 매개 변수는 HttpRequest 객체로, authenticate 함수에 제공되지 않은 경우 None을 반환한다.
# get_user : 사용자 ID를 매개 변수로 취해서 user 객체를 반환해야 한다.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'account.authentication.EmailAuthBackend',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.google.GoogleOAuth2'
]

SOCIAL_AUTH_FACEBOOK_KEY = os.getenv("SOCIAL_AUTH_FACEBOOK_KEY") # Facebook App ID
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv("SOCIAL_AUTH_FACEBOOK_SECRET") # Facebook App Secret
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

SOCIAL_AUTH_TWITTER_KEY = os.getenv("SOCIAL_AUTH_TWITTER_KEY") # Twitter API Key
SOCIAL_AUTH_TWITTER_SECRET = os.getenv("SOCIAL_AUTH_TWITTER_SECRET") # Twitter API Secret
#NtF8PpcSVyLBu76Ne--FqyC5J9x8A6NRcGaF_Uk5fdYtokf5J2

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY") # Google Client ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET") # Google Client Secret

# 파이썬 인증에서 사용하는 기본 인증 파이프라인이다. 사용자를 인증할 때 다양한 작업을 수행하는 여러 기능으로 구성된다.
SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'account.authentication.create_profile',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
]

THUMBNAIL_DEBUG = True